### ISSUE TITLE
Bincode is 2x-4x slower than serde-bench format

### ISSUE THREAD

**Issue by dtolnay** [TyOverby/bincode#123]
Check out `cargo bench` in https://github.com/serde-rs/bench. On my computer:

```
test bincode_deserialize ... bench:          42 ns/iter (+/- 0)
test bincode_serialize   ... bench:          82 ns/iter (+/- 1)
test serde_deserialize   ... bench:          24 ns/iter (+/- 0)
test serde_serialize     ... bench:          20 ns/iter (+/- 1)
```

The format is byte-for-byte identical (`cargo test` to confirm) so there should be no reason that Bincode would take 75% longer to deserialize and 310% longer to serialize in the SizeLimit::Infinite / &[u8] case.

In addition to all the tickets I filed today, see if you can identify other optimizations that would close this gap.

cc @maciejhirsz

**Comment by TyOverby** [comment]
I would expect that endianness and the current non-trait-based size limit is responsible for most of this.

**Comment by dtolnay** [comment]
Both are using big-endian. I think it's all size limit.

**Comment by TyOverby** [comment]
I made a benchmarking tool here: https://github.com/TyOverby/bincode-bench

I played around with a few optimizations, and the https://github.com/TyOverby/bincode/pull/127 PR is twice as fast as serde-bench due to the "size-find and then pre-alloc" optimization.

Somehow this is actually faster than having an already-pre-allocated array.

```
bincode writer    : 334332ns 
serde-bench (ser) : 421333ns
bincode to vec    : 197910ns
```

Decoding is almost always the same speed.

**Comment by TyOverby** [comment]
@dtolnay: could you run your benchmark suite to confirm?

**Comment by dtolnay** [comment]
I get similar results. Nice work.

**Comment by TyOverby** [comment]
🎈 🎈 🎈 🎈 🎈
