### ISSUE TITLE
Make `i128` support automatic

### ISSUE THREAD

**Issue by dhardy** [TyOverby/bincode#250]
To revisit #236, it would be more convenient for users if `i128` support was enabled automatically on compatible compilers. We [already argued in July](https://github.com/rust-random/rand/pull/571) that this was the best option for Rand.

The linked PR shows how this can be achieved without any breakage (except for old nightlies, which are generally not possible to ensure support for anyway).

**Comment by dhardy** [comment]
Since build scripts cannot enable features, this would actually require that @BurntSushi's [byteorder](https://github.com/BurntSushi/byteorder) also use auto-detection, and then that `bincode` depend on the new version of `byteorder`.

**Comment by dhardy** [comment]
We haven't had any issues — but I don't believe this implemented for the 0.5 release, and 0.6 is still pending, so it hasn't had a lot of testing.

**Comment by dhardy** [comment]
As [@newpavlov points out](https://github.com/rust-random/small-rngs/pull/10#discussion_r223633078), we shouldn't have to depend on `bincode` just to enable a feature in case users want to use binary serialisation (in this case, the type being serialised uses `u128`).

Users of old (pre-1.26) stable compilers can't use `i128` anyway, and we shouldn't care about old nightlies, so the only effects of auto-enabling this are: (1) users of recent compilers don't have to bother with the `i128` feature any more.

I was going to add (2), users may not notice when they do something losing backwards compatibility. But (a) the only way to ensure this is to test and (b) `i128` obviously requires >= 1.26 anyway.

Conclusion: I don't think there's any reason *not* to do this.

**Comment by TyOverby** [comment]
This seems reasonable to me; If @BurntSushi thinks that this is a good solution for byteorder, I'll implement it for bincode.

**Comment by BurntSushi** [comment]
Yeah I've tried hard to think about downsides to this. Changing the public API of a library based on the compiler version makes me very nervous, but I'm having a hard time finding concrete examples to justify it. One thing that pops to mind is viewing the docs for a library which contain new API items because the docs were generated with a newer compiler, while developing on an older compiler and being surprised when a public API item isn't available. AIUI, I think the first error message they'll see is "some_thing is not available" rather than "some_thing uses u128 which isn't available on your Rust 1.22 compiler." So I could see the failure modes being pretty mystifying here. I don't know how heavily to weight them though.

Since this is going to impact foundational crates, I'd feel more comfortable if we got more eyes on this issue. I opened an internals thread: https://internals.rust-lang.org/t/trade-offs-for-adding-new-apis-based-on-compiler-version/8549

**Comment by BurntSushi** [comment]
@dhardy Oh, sorry, I had assumed that my [comment here](https://internals.rust-lang.org/t/trade-offs-for-adding-new-apis-based-on-compiler-version/8549/6?u=burntsushi) meant that I was good with version sniffing and automatically adding `u128` to the public API. I don't know when exactly I'd get around to actually doing it, but it seems like it should be easy to [copy the version sniffing from regex](https://github.com/rust-lang/regex/blob/d4b9419ed41907d5e8b43166ce7aef77e6fb93d9/build.rs#L38-L86) and add a new cfg knob.

**Comment by dhardy** [comment]
It should be even easier than that; please see this PR: https://github.com/rust-random/rand/pull/664

@TyOverby would you like to prepare this for both crates? Otherwise I can make a PR.

**Comment by BurntSushi** [comment]
Interesting. I linked to the way I did it in regex to specifically avoid adding a new crate dep, but I hadn't seen `autocfg` before. Its README inspires confidence. @dtolnay As someone who I know has been fairly fastidious about adding deps for detecting rustc versions, what do you think about [`autocfg`](https://github.com/cuviper/autocfg)?

**Comment by dtolnay** [comment]
I do basically the way regex does it (for example [here in serde](https://github.com/serde-rs/serde/blob/v1.0.84/serde/build.rs) and [here in syn](https://github.com/dtolnay/syn/blob/0.15.23/build.rs)). But I like autocfg and wouldn't mind if it takes off.

Whether you use it will depend on whether you want to be an early adopter (where people might notice the extra 1 second compile time or decide not to use your crate because managing two external crates in their non-Cargo build environment isn't worth it) or a late adopter (by which time every nontrivial project already pulls in autocfg anyway).

**Comment by BurntSushi** [comment]
@dtolnay Thanks for your thoughts! That's a good point about early/late adopter. For byteorder, it's probably a good idea to be a late adopter. Although, I could see using it for regex since it already has several external crate dependencies.

**Comment by BurntSushi** [comment]
`byteorder 1.3.0` now automatically enables `i128` support for Rust >= 1.26.
