### ISSUE TITLE
Sync to cargo.io

### ISSUE THREAD

**Issue by lambdaburrito** [TyOverby/bincode#29]
Got another bincode build issue.

    /home/pez/.cargo/registry/src/github.com-1ecc6299db9ec823/bincode-0.0.13/src/reader.rs:126            self.read += cast(count).unwrap();
                                                                                                                ^~~~~~~~~~~~~~~~~~~~
    error: aborting due to previous error
    Build failed, waiting for other jobs to finish...
    Could not compile `bincode`.

Look at the current master, it seems you have fixed this but it's not sync up to Cargo.io

I would greatly appreciate if you would automate a sync between your master and Cargo.io so you don't forget. I'm running a startup and it causes productivity problems :(

**Comment by TyOverby** [comment]
Can you depend on the git version instead of crates.io?  I'm disconnected from the internet for most of the day and can't always compile and publish.

Right now I can't publish because `byteorder` is broken https://github.com/BurntSushi/byteorder/pull/24 because `rand` is broken https://github.com/rust-lang/rand/pull/42

**Comment by TyOverby** [comment]
Updated

**Comment by lambdaburrito** [comment]
Thanks for the quick resolution. Yeah, I will depend on the git version now :+1:
