### ISSUE TITLE
"bincode does not support Deserializer::deserialize"

### ISSUE THREAD

**Issue by mikedilger** [TyOverby/bincode#85]
Is this something that could be implemented, or does it mean my code is doing something wrong?

I'm trying to deserialize a `chrono::NaiveDateTime` which bincode serialized just fine.

**Comment by mikedilger** [comment]
Actually it serialized as "2016-08-16T16:41:52.757059590"... which I guess breaks the "no fluff" premise of bincode... but I think the way serde is designed it leaves things up to the type definer so not much can be done about that AFAIK.

**Comment by dtolnay** [comment]
Looks like a bug in chrono.

https://github.com/lifthrasiir/rust-chrono/blob/d50546a5925b8689f6bcca7155a7af89f2839a32/src/naive/datetime.rs#L892

It should be calling `deserializer.deserialize_str` instead of `deserializer.deserialize`.

@mikedilger to understand why this is a problem: `deserialize` expects the deserializer to be able to tell from the input what data type is there. For example JSON can see a curly brace `{` and know that that means a map, or it can see a quote `"` and know that that means a string. For performance reasons bincode does not serialize any of this fluff punctuation so it has no way to tell from the input what type is there. Serde handles this by letting Deserialize implementations hint to the deserializer what type it expects to deserialize, which they do by calling methods like `deserialize_str` instead of plain `deserialize`.

**Comment by dtolnay** [comment]
I made a chrono PR with a fix https://github.com/lifthrasiir/rust-chrono/pull/89.

**Comment by lifthrasiir** [comment]
@mikedilger

> Actually it serialized as "2016-08-16T16:41:52.757059590"... which I guess breaks the "no fluff" premise of bincode...

I plan to do something about that in Chrono 0.3. As far as I understand, the ability to change the representation per the (de)serializer is heavily dependent of the specialization.

**Comment by mikedilger** [comment]
@dtolnay @lifthrasiir Thanks!
